package models

const (
	ORAKKI_STATE_INIT = iota
	ORAKKI_STATE_READY
	ORAKKI_STATE_PAUSED
	ORAKKI_STATE_PLAYING
	ORAKKI_STATE_EXIT
)

const MSG_HELLO = "MSG_HELLO"

const MSG_FETCH_ORAKKI_STATE = "MSG_FETCH_ORAKKI_STATE"
